// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtlgcbqufokwfwdphlig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0bGdjYnF1Zm9rd2Z3ZHBobGlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjM4MjEsImV4cCI6MjA2NDAzOTgyMX0.M3uXT7U6GsxdaPNyVyST8dSlIR5Nmxcg9-i0rs2E068";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);